#!/usr/bin/perl
#
# Plugin to monitor thermal sensors inside ThinkPad
#
# Origional Author: Kamen Naydenov
# Contributors:
#
# Parameters:
#
# 	config   (required)
# 	autoconf (optional - only used by munin-config)
#

use warnings;
use strict;

if ($ARGV[0] and $ARGV[0] eq "autoconf")
  {
    if (-r "/proc/acpi/ibm/thermal")
      {
	print "yes\n";
	exit 0;
      }
    else
      {
	print "/proc/acpi/ibm/thermal not found\n You must load ibm_acpi kernel module\n";
	exit 1;
      }
  }

my ($i, $val, @sensors, @values);

@sensors=qw/CPU MiniPCI HDD GPU Bat0 Na0 Bat1 Na1/;
$val=qx|cat /proc/acpi/ibm/thermal|;

if ($ARGV[0] and $ARGV[0] eq "config")
  {
    print "graph_args --base 1000 -l 0 --vertical-label Temp\n";
    print "graph_title Some temperatures in ThinkPad\n";
    print "graph_category sensors\n";
    print "graph_info There is some themperatures detected by ibm_acpi kernel module. The location of sensors may vary on other models (these are for R51)\n";
    print "graph_order @sensors\n";
    print "graph_scale off\n";
    for (@sensors) {
      print "$_.label $_\n";
      print "$_.info Temperature near $_\n";
      print "$_.max 100\n";
    }
    exit 0;
  }

@values=split(/:|\s+/,$val);
shift @values;
shift @values;

for ($i=0; $i <= 7; $i++) {
  if ($values[$i]=~/^-(\d*)$/) {
    print "$sensors[$i].value $1\n";
  } else {
    print "$sensors[$i].value $values[$i]\n";
  }
}
